<a href="https://colab.research.google.com/github/alexandrebarbosa-dev/desafioTelecomX_BR/blob/main/TelecomX_BR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#📌 Extracão

Para iniciar sua análise, você precisará importar os dados da API da Telecom X. Esses dados estão disponíveis no formato JSON e contêm informações essenciais sobre os clientes, incluindo dados demográficos, tipo de serviço contratado e status de evasão.

O que você deve fazer:

✅ Carregar os dados diretamente da API utilizando Python.

✅ Converter os dados para um DataFrame do Pandas para facilitar a manipulação.

In [300]:
import pandas as pd

In [301]:
url = 'https://raw.githubusercontent.com/ingridcristh/challenge2-data-science/refs/heads/main/TelecomX_Data.json'
dados = pd.read_json(url)
dados.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [302]:
df = pd.json_normalize(dados.to_dict(orient='records'))
df.head()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [303]:
df.shape

(7267, 21)

#🔧 Transformação

Agora que você extraiu os dados, é fundamental entender a estrutura do dataset e o significado de suas colunas. Essa etapa ajudará a identificar quais variáveis são mais relevantes para a análise de evasão de clientes.

📌 Para te auxiliar nesse processo, criamos um dicionário de dados com a descrição de cada coluna. Embora não seja obrigatório utilizá-lo, ele pode facilitar a compreensão das informações disponíveis.

[🔗 link do dicionario junto com a api](https://github.com/ingridcristh/challenge2-data-science/blob/main/TelecomX_dicionario.md)

O que você deve fazer:

✅ Explorar as colunas do dataset e verificar seus tipos de dados.

✅ Consultar o dicionário para entender melhor os significados das variáveis.

✅ Identificar as colunas mais relevantes para a análise de evasão.

#### Dicionário de dados

* `customerID`: número de identificação único de cada cliente
* `Churn`: se o cliente deixou ou não a empresa
* `gender`: gênero (masculino e feminino)
* `SeniorCitizen`: informação sobre um cliente ter ou não idade igual ou maior que 65 anos
* `Partner`:  se o cliente possui ou não um parceiro ou parceira
* `Dependents`: se o cliente possui ou não dependentes
* `tenure`:  meses de contrato do cliente
* `PhoneService`: assinatura de serviço telefônico
* `MultipleLines`: assisnatura de mais de uma linha de telefone
* `InternetService`: assinatura de um provedor internet
* `OnlineSecurity`: assinatura adicional de segurança online
* `OnlineBackup`: assinatura adicional de backup online
* `DeviceProtection`: assinatura adicional de proteção no dispositivo
* `TechSupport`: assinatura adicional de suporte técnico, menos tempo de espera
* `StreamingTV`: assinatura de TV a cabo
* `StreamingMovies`: assinatura de streaming de filmes
* `Contract`: tipo de contrato
* `PaperlessBilling`: se o cliente prefere receber online a fatura
* `PaymentMethod`: forma de pagamento
* `Charges.Monthly`: total de todos os serviços do cliente por mês
* `Charges.Total`: total gasto pelo cliente

In [304]:
df.head()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [305]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [306]:
df.dtypes

customerID                    object
Churn                         object
customer.gender               object
customer.SeniorCitizen         int64
customer.Partner              object
customer.Dependents           object
customer.tenure                int64
phone.PhoneService            object
phone.MultipleLines           object
internet.InternetService      object
internet.OnlineSecurity       object
internet.OnlineBackup         object
internet.DeviceProtection     object
internet.TechSupport          object
internet.StreamingTV          object
internet.StreamingMovies      object
account.Contract              object
account.PaperlessBilling      object
account.PaymentMethod         object
account.Charges.Monthly      float64
account.Charges.Total         object
dtype: object

COLUNAS RELEVANTES #### Dicionário de dados

* `Churn`: se o cliente deixou ou não a empresa
* `gender`: gênero (masculino e feminino)
* `SeniorCitizen`: informação sobre um cliente ter ou não idade igual ou maior que 65 anos
* `Partner`:  se o cliente possui ou não um parceiro ou parceira
* `Dependents`: se o cliente possui ou não dependentes
* `tenure`:  meses de contrato do cliente **negrito**
* `Contract`: tipo de contrato
* `PaymentMethod`: forma de pagamento
* `TechSupport`: assinatura adicional de suporte técnico, menos tempo de espera
* `Charges.Monthly`: total de todos os serviços do cliente por mês
* `Charges.Total`: total gasto pelo cliente

## Verificando Inconsistências nos Dados

In [307]:
df['Churn'].unique()

array(['No', 'Yes', ''], dtype=object)

In [308]:
df['customer.gender'].unique()

array(['Female', 'Male'], dtype=object)

In [309]:
df['customer.Partner'].unique()

array(['Yes', 'No'], dtype=object)

In [310]:
df['customer.Dependents'].unique()

array(['Yes', 'No'], dtype=object)

In [311]:
df['account.Contract'].unique()

array(['One year', 'Month-to-month', 'Two year'], dtype=object)

In [312]:
df['account.PaymentMethod'].unique()

array(['Mailed check', 'Electronic check', 'Credit card (automatic)',
       'Bank transfer (automatic)'], dtype=object)

In [313]:
df['internet.TechSupport'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [314]:
df['account.Charges.Total'].unique()

array(['593.3', '542.4', '280.85', ..., '742.9', '4627.65', '3707.6'],
      dtype=object)

In [315]:
# Verificando todas as colubas object de uma vez e não uma por uma
colunas_categoricas = df.select_dtypes(include='object').columns
for coluna in colunas_categoricas:
    print(f'\nColuna: {coluna}')
    print(df[coluna].unique())

Coluna: customerID
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']

Coluna: Churn
['No' 'Yes' '']

Coluna: customer.gender
['Female' 'Male']

Coluna: customer.Partner
['Yes' 'No']

Coluna: customer.Dependents
['Yes' 'No']

Coluna: phone.PhoneService
['Yes' 'No']

Coluna: phone.MultipleLines
['No' 'Yes' 'No phone service']

Coluna: internet.InternetService
['DSL' 'Fiber optic' 'No']

Coluna: internet.OnlineSecurity
['No' 'Yes' 'No internet service']

Coluna: internet.OnlineBackup
['Yes' 'No' 'No internet service']

Coluna: internet.DeviceProtection
['No' 'Yes' 'No internet service']

Coluna: internet.TechSupport
['Yes' 'No' 'No internet service']

Coluna: internet.StreamingTV
['Yes' 'No' 'No internet service']

Coluna: internet.StreamingMovies
['No' 'Yes' 'No internet service']

Coluna: account.Contract
['One year' 'Month-to-month' 'Two year']

Coluna: account.PaperlessBilling
['Yes' 'No']

Coluna: account.PaymentMethod
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']

Coluna: account.Charges.Total
['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

In [316]:
colunas_numericas = df.select_dtypes(include=['int64', 'float64']).columns
colunas_numericas

Index(['customer.SeniorCitizen', 'customer.tenure', 'account.Charges.Monthly'], dtype='object')

In [317]:
df[colunas_numericas].describe()

       customer.SeniorCitizen  customer.tenure  account.Charges.Monthly
count             7267.000000      7267.000000              7267.000000
mean                 0.162653        32.346498                64.720098
std                  0.369074        24.571773                30.129572
min                  0.000000         0.000000                18.250000
25%                  0.000000         9.000000                35.425000
50%                  0.000000        29.000000                70.300000
75%                  0.000000        55.000000                89.875000
max                  1.000000        72.000000               118.750000

Resultado da análise das colunas:

Ao rodar os códigos que detalham o conteúdo das colunas, verifiquei as seguintes incossistências:

1 - Coluna ***Churn*** retorna ['No' 'Yes' ''], ou seja, há strings vazias.

2 - Coluna ***account.Charges.Total*** retorna o valor	*object*, quando deveria ser números. Isso acontece porque há strings vazias nessa coluna.

## Tratando as Inconsistências

In [318]:
(df['Churn'] == '').sum()

np.int64(224)

In [319]:
df['Churn'] = df['Churn'].replace('', pd.NA)

In [320]:
(df['Churn'] == '').sum()

np.int64(0)

In [321]:
df[colunas_numericas].describe()

       customer.SeniorCitizen  customer.tenure  account.Charges.Monthly
count             7267.000000      7267.000000              7267.000000
mean                 0.162653        32.346498                64.720098
std                  0.369074        24.571773                30.129572
min                  0.000000         0.000000                18.250000
25%                  0.000000         9.000000                35.425000
50%                  0.000000        29.000000                70.300000
75%                  0.000000        55.000000                89.875000
max                  1.000000        72.000000               118.750000

In [322]:
df['Churn'].unique()

array(['No', 'Yes', <NA>], dtype=object)

In [323]:
df = df.dropna(subset=['Churn'])

In [324]:
df['Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [325]:
df['account.Charges.Total'].unique()

array(['593.3', '542.4', '280.85', ..., '742.9', '4627.65', '3707.6'],
      dtype=object)

In [326]:
df['account.Charges.Total'] = pd.to_numeric(
    df['account.Charges.Total'],
    errors='coerce'
)

In [340]:
df['account.Charges.Total']

0        593.30
1        542.40
2        280.85
3       1237.85
4        267.40
         ...
7262     742.90
7263    1873.70
7264      92.75
7265    4627.65
7266    3707.60
Name: account.Charges.Total, Length: 7043, dtype: float64

Ao tentar converter a coluna Charges.Total para numérica, retornou um erro, indicando strings vazias. Ao fazer a análise do DF como um todo, verifiquei que isso aconteceu porque a coluna customer.tenure é igual a zero, ou seja, este é um cliente que acabou de fazer sua assinatura, não tendo gerado valores ainda. Logo, o ideal para a coluna Charges.Total é que seja igual a zero também, em vez de remover, por exemplo.

In [327]:
df['account.Charges.Total'] = df['account.Charges.Total'].astype(float)

In [337]:
df.dtypes

customerID                    object
Churn                          int64
customer.gender               object
customer.SeniorCitizen         int64
customer.Partner               int64
customer.Dependents            int64
customer.tenure                int64
phone.PhoneService             int64
phone.MultipleLines           object
internet.InternetService      object
internet.OnlineSecurity       object
internet.OnlineBackup         object
internet.DeviceProtection     object
internet.TechSupport          object
internet.StreamingTV          object
internet.StreamingMovies      object
account.Contract              object
account.PaperlessBilling       int64
account.PaymentMethod         object
account.Charges.Monthly      float64
account.Charges.Total        float64
Contas_Diarias               float64
dtype: object

## Coluna de Contas Diárias (Opcional)

In [329]:
df['Contas_Diarias'] = df['account.Charges.Monthly'] / 30

In [330]:
df[['account.Charges.Monthly', 'Contas_Diarias']].head()

   account.Charges.Monthly  Contas_Diarias
0                     65.6        2.186667
1                     59.9        1.996667
2                     73.9        2.463333
3                     98.0        3.266667
4                     83.9        2.796667

## Padronização e Transformação de Dados (Opcional)

In [331]:
colunas_relevantes = [
    'Churn',
    'customer.gender',
    'customer.SeniorCitizen',
    'customer.Partner',
    'customer.Dependents',
    'customer.tenure',
    'account.Contract',
    'account.PaymentMethod',
    'internet.TechSupport',
    'account.Charges.Monthly',
    'account.Charges.Total'
]

In [332]:
df_analise = df[colunas_relevantes].copy()
df_analise.head()

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,account.Contract,account.PaymentMethod,internet.TechSupport,account.Charges.Monthly,account.Charges.Total
0,No,Female,0,Yes,Yes,9,One year,Mailed check,Yes,65.6,593.30
1,No,Male,0,No,No,9,Month-to-month,Mailed check,No,59.9,542.40
2,Yes,Male,0,No,No,4,Month-to-month,Electronic check,No,73.9,280.85
3,Yes,Male,1,Yes,No,13,Month-to-month,Electronic check,No,98.0,1237.85
4,Yes,Female,1,Yes,No,3,Month-to-month,Mailed check,Yes,83.9,267.40

In [333]:
colunas_binarias = []

for col in df.columns:
    if df[col].dtype == 'object':
        valores = set(df[col].dropna().unique())
        if valores == {'Yes', 'No'}:
            colunas_binarias.append(col)

colunas_binarias

['Churn',
 'customer.Partner',
 'customer.Dependents',
 'phone.PhoneService',
 'account.PaperlessBilling']

In [334]:
for col in colunas_binarias:
    print(col, df[col].isna().sum())

Churn 0
customer.Partner 0
customer.Dependents 0
phone.PhoneService 0
account.PaperlessBilling 0

In [335]:
for col in colunas_binarias:
    df[col] = df[col].map({'Yes': 1, 'No': 0}).astype('int64')

In [336]:
df_analise.head()

,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,account.Contract,account.PaymentMethod,internet.TechSupport,account.Charges.Monthly,account.Charges.Total
0,No,Female,0,Yes,Yes,9,One year,Mailed check,Yes,65.6,593.30
1,No,Male,0,No,No,9,Month-to-month,Mailed check,No,59.9,542.40
2,Yes,Male,0,No,No,4,Month-to-month,Electronic check,No,73.9,280.85
3,Yes,Male,1,Yes,No,13,Month-to-month,Electronic check,No,98.0,1237.85
4,Yes,Female,1,Yes,No,3,Month-to-month,Mailed check,Yes,83.9,267.40

In [341]:
df_analise.describe()

,customer.SeniorCitizen,customer.tenure,account.Charges.Monthly,account.Charges.Total
count,7043.000000,7043.000000,7043.000000,7032.000000
mean,0.162147,32.371149,64.761692,2283.300441
std,0.368612,24.559481,30.090047,2266.771362
min,0.000000,0.000000,18.250000,18.800000
25%,0.000000,9.000000,35.500000,401.450000
50%,0.000000,29.000000,70.350000,1397.475000
75%,0.000000,55.000000,89.850000,3794.737500
max,1.000000,72.000000,118.750000,8684.800000

#📊 Carga e análise

#📄Relatorio Final